[package]
name = "adventofcode2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.49"
itertools = "0.10.1"
pathfinding = "2.2.2"
bitstream-io = "1.2.0"
hex = "0.4.3"